CREATE TABLE `vst_member` (
  `vst_uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vst_userid` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `vst_email` VARCHAR(64) DEFAULT NULL,
  `vst_email_lock` TINYINT(1) NOT NULL DEFAULT '0',
  `vst_password` VARCHAR(32) NOT NULL DEFAULT '',
  `vst_admin_pass` VARCHAR(16) NOT NULL DEFAULT '',
  `vst_name` VARCHAR(24) NOT NULL DEFAULT '',
  `vst_tel` VARCHAR(16) NOT NULL DEFAULT '0',
  `vst_tel_lock` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0:未锁定,1:锁定',
  `vst_qq` INT(11) NOT NULL DEFAULT '0',
  `vst_zip` INT(6) NOT NULL DEFAULT '0',
  `vst_sex` TINYINT(1) NOT NULL DEFAULT '0',
  `vst_card` VARCHAR(18) NOT NULL DEFAULT '0',
  `vst_point` INT(11) NOT NULL DEFAULT '0',
  `vst_money` DECIMAL(9,2) DEFAULT '0.00',
  `vst_group` TINYINT(1) NOT NULL DEFAULT '0',
  `vst_level` INT(1) NOT NULL DEFAULT '0',
  `vst_onlook` TINYINT(1) NOT NULL DEFAULT '0',
  `vst_ontime` INT(10) NOT NULL DEFAULT '0',
  `vst_lock` TINYINT(1) NOT NULL DEFAULT '1',
  `vst_viptime` INT(10) NOT NULL DEFAULT '0',
  `vst_regtime` INT(10) NOT NULL DEFAULT '0',
  `vst_login_cs` INT(11) NOT NULL DEFAULT '0',
  `vst_login_ip1` VARCHAR(15) NOT NULL DEFAULT '127.0.0.1',
  `vst_login_ip2` VARCHAR(15) NOT NULL DEFAULT '127.0.0.1',
  `vst_login_time1` INT(10) NOT NULL DEFAULT '0',
  `vst_login_time2` INT(10) NOT NULL DEFAULT '0',
  `vst_address` TEXT,
  `vst_logo` TEXT,
  `vst_info` TEXT,
  `vst_pushkey` TEXT,
  `vst_wxid` VARCHAR(50) DEFAULT NULL,
  `vst_qqid` VARCHAR(36) DEFAULT NULL,
  PRIMARY KEY (`vst_uid`),
  UNIQUE KEY `vst_uid` (`vst_uid`),
  KEY `vst_show_level` (`vst_show_level`),
  KEY `vst_uid_md5` (`vst_uid_md5`)
) ENGINE=MYISAM AUTO_INCREMENT=6070403 DEFAULT CHARSET=utf8;
